<?php

$DB_CONNSTRING = "mysql:host="; // DO NOT EDIT THIS LINE
$DB_CONNSTRING .= "db.dayz.st:3306"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE HOST:PORT (PROBABLY db.dayz.st:3306)
$DB_CONNSTRING .= ";dbname="; // DO NOT EDIT THIS LINE
$DB_CONNSTRING .= "yourdatabasename"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE NAME
$DB_USERNAME = "yourdatabaseusername"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE USERNAME
$DB_PASSWORD = "yourdatabasepassword"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE PASSWORD
$ST_PASSWORD = "yourdayzstpassword"; // EDIT THIS LINE, THIS SHOULD BE YOUR DAYZ.ST LOGIN PASSWORD

define("URLVARS", "u=dayzstuser&p=dayzstpasswordhash"); // WHEN YOU OPEN THE MAP, COPY THE PART IN THE URL AFTER http://dayz.st/map?

// Do not edit anything below this line

$salt = substr(md5(date("F")), 8); // DO NOT EDIT THIS LINE
$ST_USERNAME = explode("&", URLVARS); // DO NOT EDIT THIS LINE
$ST_USERNAME = explode("=", $ST_USERNAME[0]); // DO NOT EDIT THIS LINE
$ST_USERNAME = $ST_USERNAME[1]; // DO NOT EDIT THIS LINE
$DB_NAME = explode(";", $DB_CONNSTRING); // DO NOT EDIT THIS LINE
$DB_NAME = explode("=", $DB_NAME[1]); // DO NOT EDIT THIS LINE
$DB_NAME = $DB_NAME[1]; // DO NOT EDIT THIS LINE

?>
