<?php

$DB_CONNSTRING = "mysql:host="; // DO NOT EDIT THIS LINE
$DB_CONNSTRING .= "db.dayz.st:3306"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE HOST:PORT (PROBABLY db.dayz.st:3306)
$DB_CONNSTRING .= ";dbname="; // DO NOT EDIT THIS LINE
$DB_CONNSTRING .= "yourdatabasename"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE NAME
$DB_USERNAME = "yourdatabaseusername"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE USERNAME
$DB_PASSWORD = "yourdatabasepassword"; // EDIT THIS LINE, THIS SHOULD BE THE DATABASE PASSWORD
$ST_PASSWORD = "yourdayzstpassword"; // EDIT THIS LINE, THIS SHOULD BE YOUR DAYZ.ST LOGIN PASSWORD

define("URLVARS", "u=dayzstuser&p=dayzstpasswordhash"); // WHEN YOU OPEN THE MAP, COPY THE PART IN THE URL AFTER http://dayz.st/map?

$users = array(
    // ON THE FOLLOWING LINES, USERS CAN BE ADDED. THE PASSWORDS ARE ENCODED IN MD5 FOR BETTER SECURITY
    // YOU CAN ENCRYPT PASSWORDS TO MD5 TO PUT IN HERE AT http://md5encryption.com/
    // THE DEFAULT USER IS admin WITH PASSWORD admin
    // TO ADD MORE USERS, SEPERATE THE BY COMMA. THE LAST USER SHOULD NOT HAVE A COMMA, OR THE SCRIPT WILL FAIL
    "admin" => "21232f297a57a5a743894a0e4a801fc3"
);

// DO NOT EDIT ANYTHING BELOW THIS LINE

$salt = substr(md5(date("F")), 8); // DO NOT EDIT THIS LINE
$ST_USERNAME = explode("&", URLVARS); // DO NOT EDIT THIS LINE
$ST_USERNAME = explode("=", $ST_USERNAME[0]); // DO NOT EDIT THIS LINE
$ST_USERNAME = $ST_USERNAME[1]; // DO NOT EDIT THIS LINE
$DB_NAME = explode(";", $DB_CONNSTRING); // DO NOT EDIT THIS LINE
$DB_NAME = explode("=", $DB_NAME[1]); // DO NOT EDIT THIS LINE
$DB_NAME = $DB_NAME[1]; // DO NOT EDIT THIS LINE 

?>